name: SauceDemo Regression Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Added permissions required to publish the report to GitHub Pages
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run 16 Scripts with Maven
        run: mvn clean test -DsuiteXmlFile=testng_master.xml -Dheadless=true

      # 1. Get previous history to show trends (Pass/Fail over time)
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # 2. Convert JSON files in target/allure-results into an HTML Report
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      # 3. Publish the report to the gh-pages branch
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          publish_branch: gh-pages
          force_orphan: true